import type { Metadata } from "next";
import "./globals.css";
import { Navbar01 } from '@/components/ui/shadcn-io/navbar-01';
import { Inter } from 'next/font/google'
import {
  ClerkProvider
} from '@clerk/nextjs'

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className + " min-h-screen bg-gray-100"}>
          <Navbar01 ctaHref={"/login"} className="bg-gray-100" />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
