import type { Metadata } from "next";
import "./globals.css";
import { Navbar01 } from '@/components/ui/shadcn-io/navbar-01';
import { Inter } from 'next/font/google'

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " min-h-screen bg-gray-100"}>
        <Navbar01 className="bg-gray-100" />
        {children}
      </body>
    </html>
  );
}
